{{- if .Values.gvmrLite.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gvmr-jwt
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GVMR_JWT_SHARED_SECRET: {{ .Values.gvmrLite.jwt.sharedSecret | quote }}
{{- end }}
